install!'cocoapods',:deterministic_uuids=>false
platform :ios, '9.0'

target 'JPBaoFuSDKDemo' do
  
  pod 'AFNetworking', '~> 4.0.1'
  pod 'Adjust', :git => 'https://github.com/adjust/ios_sdk.git', :tag => 'v4.29.6'
  pod 'FBSDKLoginKit'
  pod 'FBSDKCoreKit'
  
  
  pod 'FacebookSDK'
  pod 'FacebookSDK/LoginKit'
  pod 'FacebookSDK/ShareKit'
  pod 'FacebookSDK/PlacesKit'
  pod 'FBSDKMessengerShareKit'


  pod 'GTMBase64', '1.0.1'
  pod 'MBProgressHUD', '~> 1.1.0'
  pod 'Firebase/Analytics'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Messaging'
  
  #可选-集成JPBaoFuAdSDK才需要依赖以下库
  #For AdTiming SDK
  pod 'AdTimingSDK','4.1.3'

  #For Admob
  pod 'AdTimingAdmobAdapter', '3.0.1'
  pod 'Google-Mobile-Ads-SDK', '7.58.0'

  #For Facebook
  #pod 'AdTimingFacebookAdapter', '3.0.3'
  #pod 'FBAudienceNetwork', '5.7.1'

  #For Unity
  pod 'AdTimingUnityAdapter', '3.0.1'
  pod 'UnityAds', '3.4.2'

  #For Vungle
  pod 'AdTimingVungleAdapter', '3.0.1'
  pod 'VungleSDK-iOS', '6.5.3'

  #For Applovin
  pod 'AdTimingAppLovinAdapter', '3.0.2'
  pod 'AppLovinSDK', '6.11.2'

  #For Adcolony
  pod 'AdTimingAdColonyAdapter', '3.0.2'
  pod 'AdColony', '4.1.4'

  #For Tapjoy
  pod 'AdTimingTapjoyAdapter', '3.0.2'
  pod 'TapjoySDK', '12.4.2'

  #For Chartboost
  pod 'AdTimingChartboostAdapter', '3.0.1'
  pod 'ChartboostSDK', '8.1.0'

  #For Tiktok
  pod 'AdTimingTikTokAdapter', '3.0.1'
  pod 'Bytedance-UnionAD', '2.9.0.1'

  #For Mintegral
  pod 'AdTimingMintegralAdapter', '3.0.5'
  pod 'MintegralAdSDK/RewardVideoAd', '5.9.0'
  #pod 'MintegralAdSDK/InterstitialVideoAd', '5.9.0'
  #pod 'MintegralAdSDK/BannerAd', '5.9.0'

  #For GDT
  pod 'AdTimingGdtAdapter', '3.0.1'
  #pod 'GDTMobSDK', '4.11.5'

  #For IronSource
  pod 'AdTimingIronSourceAdapter', '3.0.2'
  pod 'IronSourceSDK', '6.15.0.1'
  
end
